Repository dongibuyeo/core-frontend, pull requests merged in 2024-08, with the labels that each got.

#2 Feat/#1 간편 회원가입 페이지 필드 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
Labels: feat

#4 Feat/#3 상단 네비게이션바 하단 메뉴바 버튼 컴포넌트 제작
  public/svg/.gitkeep
  public/svg/arrow-left.svg
  public/svg/challenge.svg
  public/svg/chat.svg
  public/svg/home.svg
  public/svg/index.ts
  public/svg/profile.svg
  src/app/challenge/[id]/page.tsx
  src/app/chat/page.tsx
  src/app/layout.tsx
  src/app/mypage/[id]/page.tsx
  src/app/page.tsx
  src/components/.gitkeep
  src/components/Menubar.tsx
  src/components/Navbar.tsx
  src/components/ui/Button.tsx
  src/components/ui/Container.tsx
  src/constants/.gitkeep
  src/constants/url-map.ts
  src/hooks/useMenuState.tsx
  tsconfig.json
Labels: design, feat

#6 Feat/#5 회원가입 페이지 디자인 구현 및 기능 상세 연결
  .eslintrc.json
  package-lock.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/signup/[step]/page.tsx
  src/app/signup/page.tsx
  src/components/Loader.tsx
  src/components/Provider.tsx
  src/components/ui/Button.tsx
  src/constants/regex.ts
  src/containters/.gitkeep
  src/containters/signup/EmailCheckStep.tsx
  src/containters/signup/ProfileStep.tsx
  src/containters/signup/PushStep.tsx
  src/hooks/useDebounce.ts
  src/hooks/useMenuState.ts
  src/hooks/useMenuState.tsx
  src/store/SignupStore.ts
Labels: design, feat

#9 Feat: 챌린지 카드 컴포넌트 디자인 구현
  public/image/coffee.jpg
  src/app/home/page.tsx
  src/components/ChellengeCard.tsx
  src/utils/calculateDday.ts
Labels: design, feat

#10 Feat#7 next pwa 적용
  .eslintrc.json
  next.config.mjs
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  public/image/.gitkeep
  public/image/icon-192x192.png
  public/manifest.json
  public/sw.js
  public/sw.js.map
  public/workbox-e43f5367.js
  public/workbox-e43f5367.js.map
  src/app/layout.tsx
  src/containters/signup/PushStep.tsx
  src/firebase/firebase.js
Labels: feat

#13 feat: 챌린지 상태 버튼 컴포넌트 추가
  src/app/globals.css
  src/app/home/page.tsx
  src/components/ChallengeStatusButton.tsx
  src/types/.gitkeep
  src/types/ChallengeStatus.ts
Labels: feat

#14 Feat: 기금 통장, 챌린지 통장 컴포넌트 구현
  public/sw.js.map
  src/app/home/page.tsx
  src/components/AccountCard.tsx
  src/components/FundCard.tsx
  tailwind.config.ts
Labels: design, feat

#18 Design/#15 푸시알림 페이지 디자인 작업
  public/gif/bell.gif
  public/gif/heart-face.gif
  public/svg/arrow-left.svg
  public/svg/index.ts
  public/svg/info-circle.svg
  src/app/globals.css
  src/app/home/page.tsx
  src/app/page.tsx
  src/app/signup/[step]/page.tsx
  src/components/ChallengeStatusButton.tsx
  src/components/Navbar.tsx
  src/components/ui/Button.tsx
  src/components/ui/Container.tsx
  src/constants/url-map.ts
  src/containters/signup/EmailCheckStep.tsx
  src/containters/signup/ProfileStep.tsx
  src/containters/signup/PushStep.tsx
  src/hooks/useNavState.ts
Labels: design, feat

#22 Feat/#21 마이페이지 설정 페이지 구현
  public/svg/announcement.svg
  public/svg/contact.svg
  public/svg/delete.svg
  public/svg/edit-profile.svg
  public/svg/index.ts
  public/svg/logout.svg
  public/svg/push-notification.svg
  public/svg/version.svg
  public/sw.js.map
  src/app/mypage/page.tsx
  src/app/mypage/settings/page.tsx
  src/constants/url-map.ts
  src/containters/SettingItem.tsx
Labels: feat

#20 Feat/#19 마이페이지의 내 챌린지 현황 컴포넌트 구현
  src/app/mypage/page.tsx
  src/components/ChellengeCard.tsx
  src/components/FundCard.tsx
  src/containters/mypage/MyChallengeStatusBar.tsx
  src/containters/mypage/StatusItem.tsx
Labels: feat

#27 Feat/#23 프로필 설정 페이지 구현
  public/svg/index.ts
  public/svg/lay.svg
  public/svg/moli.svg
  public/svg/pli.svg
  public/svg/profile-setting.svg
  public/svg/settings.svg
  public/svg/sol.svg
  src/app/layout.tsx
  src/app/mypage/settings/page.tsx
  src/app/mypage/settings/profile/page.tsx
  src/components/Menubar.tsx
  src/components/ui/ProfileImage.tsx
  src/constants/url-map.ts
  src/containters/RootLayoutClient.tsx
  src/containters/settings/ProfileSelector.tsx
  src/containters/settings/SettingItem.tsx
Labels: feat

#29 Feat/#28 푸시 알림 설정 페이지 구현
  src/app/mypage/page.tsx
  src/app/mypage/settings/notification/page.tsx
  src/app/mypage/settings/page.tsx
  src/components/ui/ToggleSwitch.tsx
  src/constants/url-map.ts
  src/containters/ToggleSettingItem.tsx
Labels: feat

#39 Design/#24 챌린지 상세 페이지 디자인 작업 진행중 진행예정
  public/svg/arrow-down.svg
  public/svg/arrow-left.svg
  public/svg/calendar.svg
  public/svg/flag.svg
  public/svg/index.ts
  public/svg/money-bag.svg
  public/svg/sol.svg
  public/svg/success-modal-chart.svg
  public/svg/trophy.svg
  src/app/challenge/[id]/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/mypage/settings/profile/page.tsx
  src/app/signup/[step]/page.tsx
  src/components/ChellengeCard.tsx
  src/components/Navbar.tsx
  src/components/ui/Container.tsx
  src/constants/url-map.ts
  src/containters/challenge/ChallengeRankingCard.tsx
  src/containters/challenge/[id]/ChallengeInfo.tsx
  src/containters/challenge/[id]/ChallengeRanking.tsx
  src/containters/settings/ProfileSelector.tsx
  src/containters/signup/PushStep.tsx
  src/hooks/useMenuState.ts
Labels: design, feat

#38 Feat: 소비패턴 분석 페이지 구현
  package-lock.json
  package.json
  public/svg/chart-up.svg
  public/svg/dollars-flying.svg
  public/svg/index.ts
  src/app/recommendation/page.tsx
  src/constants/url-map.ts
  src/containters/Chart.tsx
  src/containters/RootLayoutClient.tsx
Labels: feat

#41 Feat#35 이체 인풋 컴포넌트 추가
  .eslintrc.json
  src/components/AmountInput.tsx
  tailwind.config.ts
Labels: feat

#31 Feat/#30 마이페이지 구현
  package-lock.json
  package.json
  public/svg/arrow-right.svg
  public/svg/index.ts
  src/app/mypage/page.tsx
  src/app/recommendation/page.tsx
  src/components/AccountCard.tsx
  src/components/Navbar.tsx
  src/components/ui/ProfileImage.tsx
  src/components/ui/SectionTitle.tsx
  src/services/profileApi.ts
  src/types/tailwind-scrollbar-hide.d.ts
  tailwind.config.ts
Labels: feat

#50 Feat/#43 이체 계좌선택카드 모달
  public/image/toss-logo.png
  src/app/@modal/(.)modals/[type]/page.tsx
  src/app/modals/[type]/page.tsx
  src/components/AccountCard.tsx
  src/components/modals/ModalLayout.tsx
  src/components/modals/TransferAccountListModal.tsx
  src/containters/transfer/TransferAccountItem.tsx
Labels: design, feat

#52 Feat/#40 챌린지 상세 페이지마감 UI 구현
  package-lock.json
  package.json
  public/svg/index.ts
  public/svg/people.svg
  public/svg/rocket.svg
  public/sw.js
  public/sw.js.map
  public/workbox-4754cb34.js
  public/workbox-e43f5367.js
  public/workbox-e43f5367.js.map
  src/app/challenge/[id]/page.tsx
  src/app/challenge/result/[id]/page.tsx
  src/components/ChellengeCard.tsx
  src/components/FundCard.tsx
  src/components/Navbar.tsx
  src/containters/challenge/[id]/ChallengeInfo.tsx
  src/containters/challenge/[id]/ChallengeRanking.tsx
  src/containters/challenge/result/[id]/ResultChart.tsx
Labels: design, feat

#53 Feat/#49 mychallengecard 구현
  src/app/home/page.tsx
  src/components/ChallengeButton.tsx
  src/components/MyChallengeCard.tsx
Labels: feat

#48 Fix: 프로필 모달 스타일 수정
  src/app/mypage/settings/profile/page.tsx
Labels: refactoring

#46 Feat/#42 챌린지 상태 컴포넌트 챌린지 점수내역 컴포넌트 구현
  public/svg/index.ts
  public/svg/score-down.svg
  public/svg/score-up.svg
  src/app/home/page.tsx
  src/app/mypage/page.tsx
  src/components/ChallengeCard.tsx
  src/components/MiniChallengeCard.tsx
  src/components/ScoreCard.tsx
Labels: feat

#58 Design/#54 메인페이지 배너 작업 챌린지 리스트 페이지 구현
  public/gif/100.gif
  public/gif/money-flying.gif
  public/svg/arrow.svg
  public/svg/close.svg
  public/svg/index.ts
  public/svg/lay.svg
  src/app/challenge/[id]/page.tsx
  src/app/challenge/list/page.tsx
  src/app/challenge/result/[id]/page.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/app/mypage/settings/notification/page.tsx
  src/app/mypage/settings/page.tsx
  src/app/mypage/settings/profile/page.tsx
  src/app/recommendation/page.tsx
  src/app/signup/[step]/page.tsx
  src/components/ChallengeStatusButton.tsx
  src/components/Navbar.tsx
  src/components/banner/QuizBanner.tsx
  src/components/banner/RecommendBanner.tsx
  src/components/banner/index.tsx
  src/components/modals/TransferAccountListModal.tsx
  src/constants/regex.ts
  src/constants/url-map.ts
  src/containers/Chart.tsx
  src/containers/RootLayoutClient.tsx
  src/containers/ToggleSettingItem.tsx
  src/containers/challenge/[id]/ChallengeInfo.tsx
  src/containers/challenge/[id]/ChallengeRanking.tsx
  src/containers/challenge/[id]/ChallengeRankingCard.tsx
  src/containers/challenge/result/[id]/ResultChart.tsx
  src/containers/home/SavingsRecommendCard.tsx
  src/containers/mypage/MyChallengeStatusBar.tsx
  src/containers/mypage/StatusItem.tsx
  src/containers/settings/ProfileSelector.tsx
  src/containers/settings/SettingItem.tsx
  src/containers/signup/EmailCheckStep.tsx
  src/containers/signup/ProfileStep.tsx
  src/containers/signup/PushStep.tsx
  src/containers/transfer/TransferAccountItem.tsx
  src/containers/transfer/TransferFirstStep.tsx
  src/containers/transfer/TransferSecondStep.tsx
  src/containers/transfer/TransferThirdStep.tsx
  src/hooks/useMenuState.ts
Labels: design, feat

#66 Feat/#64 메인페이지 챌린지 리스트 api 연결
  src/app/challenge/list/page.tsx
  src/app/home/page.tsx
  src/components/ChallengeCard.tsx
  src/containers/RootLayoutClient.tsx
  src/services/challenges.ts
  src/types/Challenge.ts
  src/utils/formatDate.ts
Labels: feat

#68 Feat/#55 마이페이지 api 연결
  src/app/mypage/page.tsx
  src/app/mypage/settings/profile/page.tsx
  src/components/ui/ProfileImage.tsx
  src/containers/mypage/MyChallengeStatusBar.tsx
  src/containers/settings/ProfileSelector.tsx
  src/services/mypage.ts
  src/services/profileApi.ts
  src/types/ChallengeStatus.ts
  src/types/UserProfile.ts
  src/utils/getProfileImage.tsx
Labels: feat

#78 Feat/#75 내챌린지 페이지 api 연결 작업
  src/app/challenge/my/[challengeId]/page.tsx
  src/app/challenge/my/page.tsx
  src/components/ChallengeButton.tsx
  src/components/ChallengeStatusButton.tsx
  src/components/Menubar.tsx
  src/components/MyChallengeCard.tsx
  src/constants/url-map.ts
  src/containers/challenge/[id]/ChallengeInfo.tsx
  src/hooks/useMenuState.ts
  src/hooks/useNavState.ts
  src/services/challenges.ts
  src/types/MyChallenge.ts
Labels: feat

#84 Design/#81 랜딩 페이지 최소 디자인
  package-lock.json
  package.json
  public/svg/index.ts
  public/svg/landing-logo.svg
  src/app/challenge/[id]/page.tsx
  src/app/page.tsx
  src/components/LottieComponent.tsx
  src/components/Navbar.tsx
  src/components/ui/Container.tsx
  src/constants/cloud.json
  src/constants/url-map.ts
  src/containers/challenge/[id]/ChallengeInfo.tsx
Labels: feat

#76 Fix/#74 마이페이지 내 계좌 부분 수정
  src/app/mypage/page.tsx
  src/services/account.ts
  src/types/account.ts
  src/types/user.ts
Labels: fix

#72 Feat/#69 소비패턴 분석 페이지 api 연결
  src/app/home/page.tsx
  src/app/page.tsx
  src/app/recommendation/page.tsx
  src/components/ChallengeStatusButton.tsx
  src/components/banner/QuizBanner.tsx
  src/components/banner/RecommendBanner.tsx
  src/containers/challenge/[id]/ChallengeInfo.tsx
  src/containers/recommendation/Chart.tsx
  src/containers/recommendation/ChartSummary.tsx
  src/containers/recommendation/RecommendTo.tsx
  src/services/consume.ts
  src/types/Recommendation.ts
Labels: feat

#101 feat: 내챌린지 더보기 페이지 API 연결 완료
  public/sw.js
  src/components/ChallengeButton.tsx
  src/components/CompletedDetail.tsx
  src/components/NotRewardedDetail.tsx
  src/containers/mychallenge/MyChallengeDetailCard.tsx
  src/containers/mychallenge/MyChallengeFinalRefund.tsx
Labels: feat
